### ISSUE TITLE
Updates to the build system break absolute import paths 

### ISSUE THREAD

**Issue by drazenbuljovcic** [commercelayer/commercelayer-sdk#10]
**Type**: **Bug**

Hey guys!

After updating to `v2.3.7` I found that our imports (like `import * from '@commercelayer/sdk/lib/resources/...'`) do not work anymore as the entrypoint is changed from `lib/index.js` to `lib/cjs/index.js`. We still could resolve through the `cjs` path, but this change requires unexpected updates inside our codebase. 

This was introduced in this change.
https://github.com/commercelayer/commercelayer-sdk/commit/937310fcb9bce33d456bbedd062f3c8201659950

For now I have made the version strict to `v2.2.0` which does not change the build process.
This kind of change would be a breaking change as the consumers of the package need to actively update their applications to support it!
Thanks for looking into it!

**Comment by pviti** [comment]
Hi @drazenbuljovcic we have updated the build system but we haven't changed the package interface.
You should import resources directly from `@commercelayer/sdk` and not from `@commercelayer/sdk/lib/resources/...`

**Comment by drazenbuljovcic** [comment]
Hey @pviti , we were importing using this path to leverage tree shaking, so the artifacts that we are not using do not end up in our bundle. If we import what we need from directly from the `index`, `@commercelayer/sdk` which has everything exported, we are still inadvertently providing these assets for bundling. Can you advise how we could keep using specific resources directly from their focused export files and is it possible to keep the tree shaking optimizations using this approach?
Thanks!

**Comment by pviti** [comment]
Hi @drazenbuljovcic usually you should use named imports and then let your bundler do the job and shake the tree:
`import { Order } from '@commercelayer/sdk`
Are you importing modules using `require()`?

**Comment by drazenbuljovcic** [comment]
We are using exactly this syntax. `import { Order } from '@commercelayer/sdk'`
We are not sure how much the bundler is able to do these optimizations without a signified `sideEffects: false` flag.
https://webpack.js.org/guides/tree-shaking/

Anyway, most of the imports, outside the actual client, are actually ts `typings` which are not compiled into the final bundle.
Having that said, we can adjust our code to import these in a different way, so we can consider this issue closed, just to note that having these changes between minor versions is not something that is expected.

Thank you for your input!

**Comment by pviti** [comment]
You are right @drazenbuljovcic and I apologize for that. I had assumed that the resources were imported in this way and not from `sdk/lib/resources` so I didn't consider it as a breaking change.

Thank you for your help in improving our lib!

**Comment by drazenbuljovcic** [comment]
Yees, always happy to contribute!!
