### ISSUE TITLE
Add Stripe credit card payment source procedure is not clear

### ISSUE THREAD

**Issue by citlacom** [commercelayer/commercelayer-sdk#12]
Hi @pviti - We was trying to figure out how to add a stripe payment source for a guest order but got errors when following the guides:

- https://docs.commercelayer.io/developers/v/how-tos/checkout/adding-a-payment-source
- https://docs.commercelayer.io/developers/v/how-tos/payments/stripe/adding-a-stripe-payment-source#example

 We are able to successfully get the order available payment methods and select (reference) one of this methods as the order payment method but when trying to create a payment source the example from your documentation is only passing the following payload:

```
"data": {
    "type": "stripe_payments",
    "attributes": {},
    "relationships": {
      "order": {
        "data": {
          "type": "orders",
          "id": "eqkykhjlVw"
        }
      }
    }
```

With the CL SDK I'm replicating this step in the following manner:

```
  const order = myOrderEntity
  const paymentSource = {
    options: {},
    order: clClient.orders.relationship(order.id),
  }
  // Create payment method source.
  const newPaymentSource = await clClient.stripe_payments.create(paymentSource)
  console.log('NewPaymentSource: ', newPaymentSource)
```

This produces the following errors:

![Screenshot 2021-11-30 at 20 58 48](https://user-images.githubusercontent.com/802425/144121137-45aefa22-6379-4386-a0e2-dcfbe9017d39.png)

If we don't pass the options argument, the stripe_payments.create call don't produce an exception but returns undefined. Also is not clear at what step the customer needs to fill the credit card details and if that data should be passed as options, we was not able to find any example in the SDK specs tests or in the official documentation. Can you guide us on how to properly create a customer Stripe credit card payment source and associate to a guest order?

Thanks!

**Comment by pviti** [comment]
Hi @citlacom this doesn't seem to be an SDK issue, could you please post this kind of requests on our Slack channel? It would be easier for us to assist you and answer your questions as it is monitored by all the Commerce Layer team. Thank you!
