### ISSUE TITLE
Migration from js-sdk

### ISSUE THREAD

**Issue by westhouseit** [commercelayer/commercelayer-sdk#15]
Hi guys. I can't find a migration guide from the commercelayer-js-sdk to this one.

Is there one, or is it just a straight swap?

**Comment by pviti** [comment]
Hi @westhouseit - Ee have not planned a migration guide for the SDK but we can support you in making required changes to your code. Join our [community](https://commercelayer.slack.com/archives/C275LCQ68) on Slack and feel free to ask for help, we will reply asap
