### ISSUE TITLE
Denormalizing response payloads

### ISSUE THREAD

**Issue by fnandogp** [commercelayer/commercelayer-sdk#234]
I spent some time reading the source code searching for a way to use the SDK types given a Commerce Layer response, and I could not find it.

I'm currently working on an external tax calculator. From the order payload it receives, I would like to use the `Order` type as if I was fetching the data manually.

As far as I can see, internally, the SDK has the `normalize` and `denormalize` functions that help with that. However, they are not being exposed to me.

Is there a way to do it?

What I have in mind right now would be something like the following:
```typescript
const handler = (req: Request, res: Response) => {
  const order = denormalize<Order>(req.body) // `const order` is now implicitly of the `type Order`
  ...
}
```

Am I missing something? Is there an easier way to tackle that?
Any help is appreciated. Thank you!

**Comment by pviti** [comment]
Hi @fnandogp, we are evaluating internally if and when to include this feature in the SDK.
I'll keep you posted in this thread in case of news related to this topic.

**Comment by pviti** [comment]
Hi @fnandogp, we have just released the version `5.17.1` of the SDK which adds the new function `parse()` to all the resources.
This function can be used to denormalize the payload of webhooks as you were asking:

`const shipment = cl.shipments.parse(webhookPayload)`

👋

**Comment by fnandogp** [comment]
Beautiful @pviti! Thank you!

**Comment by fnandogp** [comment]
Ciao @pviti.
Quick question: do we need to initialise a CL instance to use the parse function?
From your example, is `cl` this CL instance? Which leads me to, do I need to retrieve a token to parse the payload?

```
import CommerceLayer from '@commercelayer/sdk'

const cl = CommerceLayer({
  organization: 'your-organization-slug',
  accessToken: 'your-access-token'
})

const shipment = cl.shipments.parse(webhookPayload)
```

**Comment by pviti** [comment]
Hi @fnandogp 
Webhooks are not dependent on the client instance, but currently an instance is required to have a typed resource.
However, the `parse` function does not make API calls so the access token provided will not be verified and in practice it is possible to parse resources even with a fake token.

**Comment by fnandogp** [comment]
Thank you for confirming that @pviti, it works.
