### ISSUE TITLE
Self references are not normalized

### ISSUE THREAD

**Issue by LuudJanssen** [commercelayer/commercelayer-sdk#273]
Let's say we have an order with two line items:

```json
{
  "id": "abc",
  "type": "orders",
  "line_items": [{
    "id": "111",
    "type": "line_items"
  }, {
    "id": "222",
    "type": "line_items"
  }]
}
```

When executing a CRUD action on one of the line items and including the `order` and `order.line_items` references, the normalized `order.line_items` object doesn't include the line item that the CRUD operation was executed upon:

```ts
await client.line_items.update({
  id: "111",
  quantity: 1,
}, {
  include: ["order", "order.line_items"],
})
```

returns

```ts
{
  id: "111",
  type: "line_items",
  // ...
  order: {
    id: "abc",
    type: "orders",
    // ...
    line_items: [{
      id: "222",
      type: "line_items",
    }
    // line item "111" is missing here, while it's part of the order
    ]
  },
}
```

My guess is the API doesn't return this information to save on bytes sent, but the normalization function doesn't take this circular reference into account.

Could the SDK be changed such that the line item with ID "111" would be included in the response?

**Comment by LuudJanssen** [comment]
@pviti I respectfully don't agree with this being labelled as an enhancement. Line items missing from a response sounds like a bug to me.

**Comment by pviti** [comment]
You are starting from a `line_item` and you are including (passing through the `order`) the `line_item` itself.

The API doesn't return this "self" `line_item` in the list of the `included line_items`, this is the reason why the SDK doesn't return it in the list.

We can handle this edge case post-adding the `line_item` while denormalizing the response but this would have some limitations and the `line_item` would be in some way different from the standard `included line_items` and at the moment we are not sure we want to do it.

So this is not a bug but the normal behaviour of the API (which follows the OpenAPI standard) and even if you want to consider it a bug it would be a bug of the API itself.

This is why we consider the handling of the self reference as an enhancement of the SDK
