### ISSUE TITLE
Remove Axios to make isomorphic ?

### ISSUE THREAD

**Issue by osseonews** [commercelayer/commercelayer-sdk#274]
Any chance you can build a isomorphic SDK here? Currently, you use axios for the fetch in client.ts, which makes it impossible to use this SDK on the newer edge platforms like Cloudflare Workers (NextJs Edge also, which runs on Cloudflare) or Deno. I believe if you just switched the client to simply use standard fetch, it would work fine on Cloudflare Workers/Deno.

**Comment by suhaotian** [comment]
fetch doesn't support proxy feature, and this lib use proxy stuff from axios..

**Comment by pviti** [comment]
Hi @suhaotian 👋

If we will add the support for fetch we'll modify also the support for proxies or we will remove it at all for the moment.

The SDK version which will include the support for fetch will work only with Node.js >=20.x

**Comment by michaelmerrill** [comment]
Commenting to track this issue and show support for this change. I'm currently writing fetch requests to commerce layer in server components to take advantage of NextJS RSCs. Would be great to use this library instead.

**Comment by suhaotian** [comment]
If no need proxy support, I can faster migrate axios to [xior](https://github.com/suhaotian/xior)

**Comment by pviti** [comment]
@suhaotian I think I will give `xior` a try (well, I'll try to find time to do it 🙂)

**Comment by suhaotian** [comment]
@pviti Thanks for give a try of xior!

I clone the code, after install and run pnpm test, but test failed, any documentation of how to run test locally?

<img width="748" alt="image" src="https://github.com/commercelayer/commercelayer-sdk/assets/6512574/2fe012a3-4326-471e-ba96-012f034f4bb6">

**Comment by pviti** [comment]
You need a `.env` in your root with the following variables
CL_SDK_ORGANIZATION=_\<your-organization-slug>_
CL_SDK_CLIENT_ID=_\<application-client-id>_
CL_SDK_CLIENT_SECRET=_\<application-client-secret>_

**Comment by suhaotian** [comment]
@pviti Thanks
Now it's work, but still some tests failed, what I missing?
<img width="391" alt="image" src="https://github.com/commercelayer/commercelayer-sdk/assets/6512574/15175136-bdb1-4fe1-b125-5b6d1691da8e">
