### ISSUE TITLE
Cannot update cart quantity

### ISSUE THREAD

**Issue by hari** [commercelayer/commercelayer-sdk#38]
I am trying to update the line item's quantity in the order but the API returns a validation error.

### Steps:

1. Add an SKU to the cart with `external_price` set to `true`. 
2. Try to update the quantity of the line item using `line_items.update({id, quantity})`.
3. Update fails with error `unit_amount_cents - doesn't match with the associated item one`.

I think it is because I haven't created a dedicated price for this SKU. 

### Expectation:
It should let me update the quantity as I added the item to the cart using an external pricing mechanism.

**Comment by pviti** [comment]
Hi @hari if the issue is not strictly related to the SDK but to the API itself you ca write and ask for support on our Slack channel: [https://commercelayer.slack.com](commercelayer.slack.com). There our team can better give you assistance and answer to your questions.

**Comment by hari** [comment]
@pviti Thanks. I will try to contact someone in the slack channel.
