### ISSUE TITLE
Breaking change in a minor release

### ISSUE THREAD

**Issue by drazenbuljovcic** [commercelayer/commercelayer-sdk#9]
**Type**: **Versioning issue**

Hey there!

While trying to upgrade this sdk from version `2.0.1` to `2.3.6`, I'm getting issues with the install related to my `node` version.
In the previous release the engine version was not set, but with this change the node engine version is introduced (asking for `v16.0.0`) causing the install to fail.

https://github.com/commercelayer/commercelayer-sdk/commit/4846a360701b4bcee62974a4f7e71d738faf0a7d#diff-7ae45ad102eab3b6d7e7896acd08c427a9b25b346470d7bc6507b6481575d519R72

**Node version**: `v14.18.1`

This change wouldn't be expected to land in a `minor` version following semantic versioning.

Is it related to some installed dependency necessary for this SDK?
Is it possible to backport the added changes to a stable `2.x.x` version?

**Additional note:**
There's no changelog kept in which we could find the previous version to resolve easily, which does not include these changes so we can use a stable version of this package.

**Comment by pviti** [comment]
Hi @drazenbuljovcic we will remove the Node.js engine constraint with the next release of the SDK (`2.3.7`).
Thank you for reporting this issue!

**Comment by drazenbuljovcic** [comment]
Thank you for making the change @pviti !!
